version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Usamos una imagen Docker con Python preinstalado

    steps:
      - checkout  # Clona tu repositorio

      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Ejecutar script de Python
          command: |
            . venv/bin/activate
            python script.py

      - run:
          name: Ejecutar pruebas unitarias
          command: |
            . venv/bin/activate
            python -m unittest discover tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
